version: 1
accounts:
  - name: alice
    coins: ["20000udeco", "200000000stake"]
  - name: bob
    coins: ["10000udeco", "100000000stake"]
  - name: danneh0427
    coins: ["150000000000udeco"]
  - name: decolapstestnet
    coins: ["0udeco"]
validators:
  - name: alice
    bonded: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5udeco", "100000stake"]
